name: firebase_counter
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: janamou <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  firebase: ^5.0.2
  service_worker: ^0.2.3

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1

