name: firebase_counter
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: janamou <email@example.com>

environment:
  sdk: '>=2.0.0-dev.50 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+11
  angular_components: ^0.9.0-alpha+11
  firebase: ^4.0.0

dev_dependencies:
  build_runner: ^0.8.6
  build_web_compilers: ^0.3.6
